# Generated by Django 4.0.4 on 2022-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
